"
I define examples for the class {{gtClass:BlChildrenOrderedCollection}}.

Instances of {{gtClass:BlChildrenOrderedCollection}} are created by directly instatiating the class.
{{gtExample:BlChildrenOrderedCollectionExamples>>#emptyChildrenExplicitCreation}}

Bloc elements can then be added and removed from the collection.
{{gtExample:BlChildrenOrderedCollectionExamples>>#add}}

{{gtExample:BlChildrenOrderedCollectionExamples>>#remove}}

"
Class {
	#name : #BlChildrenOrderedCollectionExamples,
	#superclass : #Object,
	#traits : 'TBlChildrenExample',
	#classTraits : 'TBlChildrenExample classTrait',
	#category : #'Bloc-Examples-Children'
}
